config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controller => {registrations: "registrations"}
  root to:  "top#index"
  resources :blogs
  get "/contacts/new" => "contacts#new"
  post "/contacts/new" => "contacts#new"
  post "/contacts/confirmation" => "contacts#confirmation"
  post "/contacts" => "contacts#create"
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.fetch(:blog, {})
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    if(params[:contact])
      @contact=Contact.new(contact_params)
    else
      @contact=Contact.new
    end
  end

  def confirmation
    @contact=Contact.new(contact_params)
    unless @contact.valid?
      render :new
    end
  end

  def create
    Contact.create(contact_params)
  end

  private
  def contact_params
    params.require(:contact).permit(:name,:email,:title,:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
    def sign_up_params
      params.require(:user).permit(:name,:email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/contacts/confirmation.html.erb
<h2>登録内容確認</h2>
<% if @contact.errors.any? %>
  <strong>入力内容にエラーがあります</strong>
  <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% else %>
  <%= form_for(@contact) do |f| %>
    <div>
      <%= "お名前:#{@contact.name}" %>
      <%= hidden_field :contact, :name %>
    </div>
    <div>
      <%= "メールアドレス:#{@contact.email}" %>
      <%= hidden_field :contact, :email %>
    </div>
    <div>
      <%= "タイトル#{@contact.title}" %>
      <%= hidden_field :contact, :title %>
    </div>
    <div>
      <%= "内容#{@contact.content}" %>
      <%= hidden_field :contact, :content %>
    </div>
    <div>
      <%= f.submit "登録する" %>
    </div>
  <% end %>
<% end %>
<%= form_for @contact,url: contacts_new_path do |f| %>
  <%= hidden_field :contact, :name %>
  <%= hidden_field :contact, :email %>
  <%= hidden_field :contact, :title %>
  <%= hidden_field :contact, :content %>
  <%= f.submit "再入力" %>
<% end %>

app/views/contacts/create.html.erb
  <h1>問い合わせいただき、ありがとうございました</h1>
  <%= link_to "メインへ", root_path %>

app/views/contacts/new.html.erb
<%= form_for @contact, url: contacts_confirmation_path do |f| %>
  <div>
    <%= f.label :name, "お名前" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email, "メールアドレス" %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :content, "内容" %>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit "登録する" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Achieve</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
    <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "btn" %>
  <% else %>
    <%= link_to "サインイン", new_user_session_path, class: "btn" %>
  <% end %>
  
  <%= yield %>

</body>
</html>

app/views/top/index.html.erb
  <h1>Top Page Of Achieve</h1>
  <%= link_to "ブログへ", blogs_path %>
  <%= link_to "お問い合わせ", contacts_new_path %>